sudo: required
services:
  - docker

#Build test image
before_install:
  - docker build -t lharo/fibonacci-react-app-test -f ./client/Dockerfile.dev ./client

#Test test image
script:
  - docker run -e CI=true lharo/fibonacci-react-app-test npm test

#Build production images
after_succes:
  - docker build -t lharo/fibonacci-app-client ./client
  - docker build -t lharo/fibonacci-app-nginx ./nginx
  - docker build -t lharo/fibonacci-app-server ./server
  - docker build -t lharo/fibonacci-app-worker ./worker

  #Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push images to docker hub

  - docker push lharo/FibonacciAppClient
  - docker push lharo/FibonacciAppNginx
  - docker push lharo/FibonacciAppServer
  - docker push lharo/FibonacciAppWorker